### PR TITLE
Not add/add S3DistCp for shredded JSONs and shredded TSVs depending on the configuration

### PR DESCRIPTION
**Pull request by benjben**
Logic:
- Not copy shredded JSONs only if shredder version >= 0.16.0 and tabularBlacklist is an empty array
- Copy shredded TSVs only if shredder version >= 0.16.0 and tabularBlacklist exists and is an array

### CODE REVIEW

**Review by istreeter — CHANGES_REQUESTED** [review]
Just in terms of the code this looks great 👍. No objections.

But... I know snowplow is trying to avoid words like "blacklist" now.  I wonder if you could swap to a different word without having too much impact on the code, e.g. blocklist?

**Comment by chuwy** [comment]
> But... I know snowplow is trying to avoid words like "blacklist" now. I wonder if you could swap to a different word without having too much impact on the code, e.g. blocklist?

That would require:

1. Iglu Central release with new major version of the schema
2. Change on infrastructure side for every client

File: lib/snowplow-emr-etl-runner/emr_job.rb [hunk 1]
```diff
@@ -48,7 +48,7 @@ class EmrJob
       SHRED_STEP_OUTPUT = 'hdfs:///local/snowplow/shredded-events/'
 
       SHRED_JOB_WITH_PROCESSING_MANIFEST = Gem::Version.new('0.14.0-rc1')
-      SHRED_JOB_WITH_TSV_OUTPUT = Gem::Version.new('0.16.0-rc1')
```
Comment (chuwy) [inline lib/snowplow-emr-etl-runner/emr_job.rb]: I'd stay with rc1 because it was first factual version with TSV. Just in case some lost soul decided to stick to RC assets.

**Review by chuwy — APPROVED** [review]
LGTM! Really glad you managed to write tests for it.

**Review by istreeter — APPROVED** [review]

**Comment by benjben** [comment]
The run failed with
```
uri:classloader:/gems/json-schema-2.7.0/lib/json-schema/util/array_set.rb:18: warning: constant ::Fixnum is deprecated
NoMethodError: undefined method `should_copy_shredded_JSONs' for #<Snowplow::EmrEtlRunner::EmrJob:0x440461ef>
       initialize at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:609
          send_to at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_reference.rb:43
        call_with at uri:classloader:/gems/contracts-0.11.0/lib/contracts/call_with.rb:76
  redefine_method at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_handler.rb:138
              run at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:135
          send_to at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_reference.rb:43
        call_with at uri:classloader:/gems/contracts-0.11.0/lib/contracts/call_with.rb:76
  redefine_method at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_handler.rb:138
           <main> at uri:classloader:/emr-etl-runner/bin/snowplow-emr-etl-runner:41
             load at org/jruby/RubyKernel.java:1009
           <main> at uri:classloader:/META-INF/main.rb:1
          require at org/jruby/RubyKernel.java:974
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
           <main> at <script>:3
ERROR: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `should_copy_shredded_JSONs' for #<Snowplow::EmrEtlRunner::EmrJob:0x440461ef>
```

File: lib/snowplow-emr-etl-runner/emr_job.rb (hunk 1 above)
Comment (benjben) [reply lib/snowplow-emr-etl-runner/emr_job.rb]: If 0.16.0-rc1 is the first version with TSV, it means that *all* 0.16.0 versions are with TSV, doesn't it?

Comment (benjben) [reply lib/snowplow-emr-etl-runner/emr_job.rb]: You were right. EER is smarter that I thought it was to compare versions, I thought that it was alphabetical comparison but no it's able to understand RC. On biz1 we're using -rc7 and it didn't work with `0.16.0`.
